CREATE TABLE Usuario (id_usuario int(10) NOT NULL AUTO_INCREMENT, codigo_anonimo varchar(32) NOT NULL UNIQUE, edad int(10) NOT NULL, `genero varchar` varchar(20) NOT NULL, experiencia varchar(20) NOT NULL, consentimiento int(10) NOT NULL, fecha_registro date NOT NULL, PRIMARY KEY (id_usuario));
CREATE TABLE Jugador (id_jugador int(10) NOT NULL AUTO_INCREMENT, alias varchar(50) NOT NULL, Usuarioid_usuario int(10) NOT NULL, PRIMARY KEY (id_jugador));
CREATE TABLE Episodio (id_episodio int(10) NOT NULL AUTO_INCREMENT, nombre_episodio varchar(80) NOT NULL, PRIMARY KEY (id_episodio));
CREATE TABLE Mapa (id_mapa int(10) NOT NULL AUTO_INCREMENT, codigo_mapa varchar(10) NOT NULL, nombre_mapa varchar(80) NOT NULL, Episodioid_episodio int(10) NOT NULL, PRIMARY KEY (id_mapa));
CREATE TABLE Sector (id_sector int(10) NOT NULL AUTO_INCREMENT, codigo_sector varchar(20) NOT NULL, coordenada_x numeric(19, 0) NOT NULL, coordenada_y numeric(19, 0) NOT NULL, Mapaid_mapa int(10) NOT NULL, PRIMARY KEY (id_sector));
CREATE TABLE Partida (`Column` int(10) NOT NULL AUTO_INCREMENT, fecha_inicio date NOT NULL, fecha_fin date NOT NULL, configuracion varchar(200) NOT NULL, Mapaid_mapa int(10) NOT NULL, PRIMARY KEY (`Column`));
CREATE TABLE `Participante Partida` (id_participante int(10) NOT NULL AUTO_INCREMENT, rol varchar(30) NOT NULL, Jugadorid_jugador int(10) NOT NULL, PartidaColumn int(10) NOT NULL, PRIMARY KEY (id_participante));
CREATE TABLE Evento_telemetria (id_evento int(20) NOT NULL AUTO_INCREMENT, tic int(10) NOT NULL, pos_x numeric(19, 0) NOT NULL, pos_y numeric(19, 0) NOT NULL, pos_z numeric(19, 0) NOT NULL, angulo numeric(19, 0) NOT NULL, momentum_x numeric(19, 0) NOT NULL, momentum_y numeric(19, 0) NOT NULL, momentum_z numeric(19, 0) NOT NULL, fov numeric(19, 0) NOT NULL, salud int(10) NOT NULL, armadura int(10) NOT NULL, municion int(10) NOT NULL, PartidaColumn int(10) NOT NULL, Jugadorid_jugador int(10) NOT NULL, Sectorid_sector int(10) NOT NULL, PRIMARY KEY (id_evento));
CREATE TABLE instrumento_ux (id_instrumento int(10) NOT NULL AUTO_INCREMENT, nombre varchar(50) NOT NULL, descripcion varchar(200) NOT NULL, PRIMARY KEY (id_instrumento));
CREATE TABLE item_ux (id_tem int(10) NOT NULL AUTO_INCREMENT, texto_pregunta varchar(200) NOT NULL, dimension varchar(40) NOT NULL, instrumento_uxid_instrumento int(10) NOT NULL, PRIMARY KEY (id_tem));
CREATE TABLE respuesta_ux (id_respuesta int(10) NOT NULL AUTO_INCREMENT, fecha_respuesta date NOT NULL, Usuarioid_usuario int(10) NOT NULL, instrumento_uxid_instrumento int(10) NOT NULL, PRIMARY KEY (id_respuesta));
CREATE TABLE respuesta_item_ux (id_respuesta_item int(10) NOT NULL AUTO_INCREMENT, valor_respuesta numeric(19, 0) NOT NULL, respuesta_uxid_respuesta int(10) NOT NULL, item_uxid_tem int(10) NOT NULL, PRIMARY KEY (id_respuesta_item));
ALTER TABLE Jugador ADD CONSTRAINT tiene FOREIGN KEY (Usuarioid_usuario) REFERENCES Usuario (id_usuario);
ALTER TABLE `Participante Partida` ADD CONSTRAINT participa_en FOREIGN KEY (Jugadorid_jugador) REFERENCES Jugador (id_jugador);
ALTER TABLE `Participante Partida` ADD CONSTRAINT FKParticipan331956 FOREIGN KEY (PartidaColumn) REFERENCES Partida (`Column`);
ALTER TABLE Mapa ADD CONSTRAINT contiene FOREIGN KEY (Episodioid_episodio) REFERENCES Episodio (id_episodio);
ALTER TABLE Sector ADD CONSTRAINT divide FOREIGN KEY (Mapaid_mapa) REFERENCES Mapa (id_mapa);
ALTER TABLE Partida ADD CONSTRAINT contextualiza FOREIGN KEY (Mapaid_mapa) REFERENCES Mapa (id_mapa);
ALTER TABLE Evento_telemetria ADD CONSTRAINT genera FOREIGN KEY (PartidaColumn) REFERENCES Partida (`Column`);
ALTER TABLE Evento_telemetria ADD CONSTRAINT produce FOREIGN KEY (Jugadorid_jugador) REFERENCES Jugador (id_jugador);
ALTER TABLE Evento_telemetria ADD CONSTRAINT FKEvento_tel226138 FOREIGN KEY (Sectorid_sector) REFERENCES Sector (id_sector);
ALTER TABLE item_ux ADD CONSTRAINT FKitem_ux413764 FOREIGN KEY (instrumento_uxid_instrumento) REFERENCES instrumento_ux (id_instrumento);
ALTER TABLE respuesta_ux ADD CONSTRAINT responde FOREIGN KEY (Usuarioid_usuario) REFERENCES Usuario (id_usuario);
ALTER TABLE respuesta_ux ADD CONSTRAINT agrupa FOREIGN KEY (instrumento_uxid_instrumento) REFERENCES instrumento_ux (id_instrumento);
ALTER TABLE respuesta_item_ux ADD CONSTRAINT detalla FOREIGN KEY (respuesta_uxid_respuesta) REFERENCES respuesta_ux (id_respuesta);
ALTER TABLE respuesta_item_ux ADD CONSTRAINT referencia FOREIGN KEY (item_uxid_tem) REFERENCES item_ux (id_tem);
